chas_universe <- c(
  "(Total: )?Owner occupied (housing units )?with no mortgage( balance)?" = "Owners with no mortgage",
  "(Total: )?Owner occupied (housing units )?with (a )?mortgage" = "Owners with mortgage",
  "(Total: )?Occupied housing units" = "Occupied housing units",
  "Tenure: All" = "Occupied housing units",
  "Owner occupied" = "Owners",
  "(Total: )?Renter occupied( housing units)?" = "Renters",
  "(Total: )?Vacant-for-sale( housing units)?" = "Vacant-for-sale",
  "(Total: )?Vacant-for-rent( housing units)?" = "Vacant-for-rent"
)

chas_variables <- tibble::tibble(
  original = c(
    "(AND race/ethnicity is )?White alone, non-Hispanic",
    "(AND race/ethnicity is )?Black or African-American alone, non-Hispanic",
    "(AND race/ethnicity is )?Asian alone, non-Hispanic",
    "(AND race/ethnicity is )?American Indian or Alaska Native alone, non-Hispanic",
    "(AND race/ethnicity is )?Pacific Islander alone, non-Hispanic",
    "(AND race/ethnicity is )?Hispanic, any race",
    "(AND race/ethnicity is )?other \\(including multiple races, non-Hispanic\\)",
    "(AND Structure built in )?1939 or earlier",
    "(AND Structure built )?between 1940 and 1959",
    "(AND Structure built )?between 1940 and 1979",
    "(AND Structure built )?between 1960 and 1979",
    "(AND Structure built )?between 1980 and 1999",
    "(AND Structure built in )?1980 or later",
    "(AND Structure built in )?2000 or later",
    "has none of the 4 housing problems OR cost burden not computed, none of the other 3 housing problems",
    "has none of the 4 severe housing problems OR cost burden not computed, none of the other 3 severe housing problems",
    "AND has none of the 4 housing unit problems \\(lacks kitchen or plumbing, more than 1 person per room, or cost burden greater than 50%\\)",
    "AND has none of the 4 housing unit problems( \\(lacks kitchen or plumbing, more than 1 person per room, or cost burden greater than 30%\\))?",
    "(AND )?has 1 or more of the 4 (severe )?housing (unit )?problems \\(lacks kitchen or plumbing, more than 1 person per room, or cost burden greater than 50%\\)",
    "(AND )?has 1 or more of the 4 housing unit problems( \\(lacks kitchen or plumbing, more than 1 person per room, or cost burden greater than 30%\\))?",
    "AND with more than 1 but less than or equal to 1.5 persons per room, none of the needs above",
    "AND with more than 1.5 persons per room, none of the needs above",
    "AND with housing cost burden greater than 50%, none of the needs above",
    "AND with housing cost burden greater than 30% but less than or equal to 50%, none of the needs above",
    "AND housing cost burden not computed, none of the needs above",
    "AND [cC]ost burden (can)?not (be )?computed, (household has )?none of the (3 )?other (3 )?housing (unit )?problems( \\(lacks kitchen or plumbing, or has more than 1 person per room\\))?",
    "(AND )?persons per room is less than or equal to 1",
    "(AND )?persons per room is greater than 1 but less than or equal to 1.5",
    "(AND )?persons per room is greater than 1.5",
    "(AND )?(housing unit )?lack(s|ing) complete (kitchen|plumbing) or (plumbing|kitchen) facilities",
    "(AND )?(housing unit )?has complete (kitchen|plumbing) and (plumbing|kitchen) facilities",
    "One unit in structure",
    "5 or more units in structure",
    "2 to 4 units in structure",
    "Other structure type \\(mobile homes, etc\\.\\)",
    "AND household income is less than or equal to 20% of HAMFI",
    "AND household income is greater than 20% but less than or equal to 30% of HAMFI",
    "AND household income is greater than 30% but less than or equal to 40% of HAMFI",
    "AND household income is greater than 40% but less than or equal to 50% of HAMFI",
    "AND household income is greater than 50% but less than or equal to 60% of HAMFI",
    "AND household income is greater than 60% but less than or equal to 65% of HAMFI",
    "AND household income is greater than 65% but less than or equal to 80% of HAMFI",
    "AND household income is greater than 80% but less than or equal to 95% of HAMFI",
    "AND household income is greater than 95% but less than or equal to 100% of HAMFI",
    "AND household income is greater than 100% but less than or equal to 115% of HAMFI",
    "AND household income is greater than 115% but less than or equal to 120% of HAMFI",
    "AND household income is greater than 120% but less than or equal to 140% of HAMFI",
    "(AND )?([hH]ousehold income )?(is )?less than or equal to 30% of HAMFI",
    "(AND )?([hH]ousehold income )?(is )?greater than 30% (of HAMFI )?but less than or equal to 50% of HAMFI",
    "(AND )?([hH]ousehold income )?(is )?greater than 50% (of HAMFI )?but less than (or equal to )?80% of HAMFI",
    "(AND )?([hH]ousehold income )?(is )?greater than 80% (of HAMFI )?but less than or equal to 100% of HAMFI",
    "(AND )?([hH]ousehold income )?(is )?greater than 100% of HAMFI",
    "(AND )?([hH]ousehold income )?(is )?greater than 80% of HAMFI",
    "less than or equal to 50% of HAMFI",
    "greater than 80% but less than 120% of HAMFI",
    "greater than 120% of HAMFI",
    "(AND )?(household income is )?greater than 140% of HAMFI",
    "(AND )?household type is one family with no subfamilies",
    "(AND )?household type is one family with at least one subfamily or more than one family",
    "(AND )?(other )?household type (is )?(\\()?non-(family|elderly) non-(elderly|family)(\\))?",
    "(AND )?household type is non-family",
    "(AND )?household type is elderly family( \\(2 persons, with either or both age 62 or over\\))?",
    "(AND )?household type is elderly non-family( \\(1 or 2 person non-family households with either person 62 years or over\\))?",
    "(AND )?household type is small family \\(2 persons, neither person 62 years or over, or 3 or 4 persons\\)",
    "(AND )?household type is large family \\(5 or more persons\\)",
    "(AND )?household type is family, no spouse\\*",
    "(AND )?household type is married couple family",
    "(AND )?(housing cost burden is )?less than or equal to 30%",
    "(AND )?(housing cost burden is )?greater than 30% but less than or equal to 50%",
    "(AND )?(housing cost burden is )?greater than 50%",
    "AND housing cost burden not computed \\(no/negative income\\)",
    "AND [vV]alue (is )?less than or equal to VHUD50",
    "AND [vV]alue (is )?greater than VHUD50 (but|and) less than or equal to VHUD80",
    "AND [vV]alue (is )?greater than VHUD80 (but|and) less than or equal to VHUD100",
    "AND [vV]alue (is )?greater than VHUD100",
    "AND number of bedrooms is 0 or 1",
    "AND number of bedrooms is 2",
    "AND number of bedrooms is 3 or more",
    "AND [rR]ent (is )?less than or equal to RHUD30",
    "AND [rR]ent (is )?greater than RHUD30 (but|and) less than or equal to RHUD50",
    "AND [rR]ent (is )?greater than RHUD50 (but|and) less than or equal to RHUD80",
    "AND [rR]ent (is )?greater than RHUD80",
    "AND household size is less than 5",
    "AND household size is 5 or more",
    "AND household contains 1 or more children age 6 or younger",
    "AND household contains no children age 6 or younger",
    "AND household contains at least 1 person age 62-74 but no one age 75\\+",
    "AND household contains at least 1 person age 75\\+",
    "AND household contains no one age 62\\+",
    "Household member has a hearing or vision impairment",
    "Household member has an ambulatory limitation",
    "Household member has a cognitive limitation",
    "Household member has a self-care or independent living limitation",
    "Household member has none of the above limitations"
  ),
  label = c(
    "White",
    "Black",
    "Asian",
    "Native",
    "Pacific Islander",
    "Hispanic",
    "Other",
    "1939 or earlier",
    "1940-1959",
    "1940-1979",
    "1960-1979",
    "1980-1999",
    "1980 or later",
    "2000 or later",
    "No housing problems or not computed and no problems",
    "No severe housing problems or not computed and no problems",
    "No severe housing problems",
    "No housing problems",
    "1 or more severe housing problems",
    "1 or more housing problems",
    "1-1.5 persons per room, no other needs",
    "1.5+ persons per room, no other needs",
    "extremely cost burdened, no other needs",
    "cost burdened, no other needs",
    "cost burden not computed, no other needs",
    "cost burden not computed, no other needs",
    "0-1 persons per room",
    "1-1.5 persons per room",
    "1.5+ persons per room",
    "lacks complete kitchen or plumbing",
    "has complete kitchen and plumbing",
    "1 unit",
    "5+ units",
    "2-4 units",
    "Other structure type",
    "0-20% HAMFI",
    "20-30% HAMFI",
    "30-40% HAMFI",
    "40-50% HAMFI",
    "50-60% HAMFI",
    "60-65% HAMFI",
    "65-80% HAMFI",
    "80-95% HAMFI",
    "95-100% HAMFI",
    "100-115% HAMFI",
    "115-120% HAMFI",
    "120-140% HAMFI",
    "0-30% HAMFI",
    "30-50% HAMFI",
    "50-80% HAMFI",
    "80-100% HAMFI",
    "100%+ HAMFI",
    "80%+ HAMFI",
    "0-50% HAMFI",
    "80-120% HAMFI",
    "120%+ HAMFI",
    "140%+",
    "Single family",
    "Multi-family",
    "non-elderly non-family",
    "non-family",
    "elderly family",
    "elderly non-family",
    "small family",
    "large family",
    "family, no spouse",
    "married couple family",
    "0-30% cost burden",
    "30-50% cost burden",
    "50%+ cost burden",
    "not computed",
    "VHUD50 or less",
    "VHUD50-VHUD80",
    "VHUD80-VHUD100",
    "VHUD100+",
    "0-1",
    "2",
    "3+",
    "RHUD30 or less",
    "RHUD30-RHUD50",
    "RHUD50-RHUD80",
    "RHUD80+",
    "less than 5",
    "5 or more",
    "1+ young children",
    "no young children",
    "1+ elderly, no very elderly",
    "1+ very elderly",
    "no elderly",
    "hearing or vision impairment",
    "ambulatory limitation",
    "cognitive limitation",
    "self-care or independent living limitation",
    "no disability"
  ),
  concept = c(
    "race",
    "race",
    "race",
    "race",
    "race",
    "race",
    "race",
    "year structure built",
    "year structure built",
    "year structure built",
    "year structure built",
    "year structure built",
    "year structure built",
    "year structure built",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    "housing problems",
    # "overcrowding",
    # "overcrowding",
    # "overcrowding",
    # "presence of plumbing or kitchen facilities",
    # "presence of plumbing or kitchen facilities",
    "units in structure",
    "units in structure",
    "units in structure",
    "units in structure",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household income",
    "household type",
    "household type",
    "household type",
    "household type",
    "household type",
    "household type",
    "household type",
    "household type",
    "household type",
    "household type",
    "cost burden",
    "cost burden",
    "cost burden",
    "cost burden",
    "home value",
    "home value",
    "home value",
    "home value",
    "number of bedrooms",
    "number of bedrooms",
    "number of bedrooms",
    "rent",
    "rent",
    "rent",
    "rent",
    "household size",
    "household size",
    "presence of young children",
    "presence of young children",
    "presence of elderly",
    "presence of elderly",
    "presence of elderly",
    "disability",
    "disability",
    "disability",
    "disability",
    "disability"
  )
)

chas_fips_geos <- tibble::tibble(
  geo = c(
    "state",
    "county",
    "mcd",
    # "remainders",
    "tract",
    "counties by place",
    "place",
    "cities"
  ),
  fips = c(
    "040",
    "050",
    "060",
    # "070",
    "140",
    "155",
    "160",
    "170"
  )
)
